
server:
    port: 8882
spring:
    application:
        name: config-client
    cloud:
        config:
           label: master
           profile: dev
           name: config-client
           uri: http://localhost:8888/
        bus:
           enabled: true
           trace:
              enabled: true
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
management:
    endpoints:
        web:
            exposure:
                include: bus-refresh
