eureka:
    client:
    # 开启健康检查
        healthcheck:
              enabled: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

    instance:
  # 续约更新时间间隔（默认30秒）
        lease-expiration-duration-in-seconds: 30
        # 续约到期时间（默认90秒）
        lease-renewal-interval-in-seconds: 10

server:
    port: 8764
spring:
    application:
        name: service-ribbon