server:
   port: 8889

eureka:
   instance:
       hostname: localhost
       prefer-ip-address: true
   server:
   # 设为false，关闭自我保护
#       enable-self-preservation: false
# 清理间隔（单位毫秒，默认是60*1000）
       eviction-interval-timer-in-ms: 4000

   client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


spring:
   application:
       name: eurka-server